#!/bin/bash

# Copied from official Docker httpd image
# https://github.com/docker-library/httpd
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec /usr/sbin/apache2ctl -D FOREGROUND